using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;

[CustomPropertyDrawer(typeof(InputString))]
public class InputStringEditor : PropertyDrawer
{
    private int _index = 0;

    private GUIStyle popupStyle;

    public override void OnGUI(Rect position, SerializedProperty property, GUIContent label)
    {
        if (popupStyle == null)
        {
            popupStyle = new GUIStyle(GUI.skin.GetStyle("PaneOptions"));
            popupStyle.imagePosition = ImagePosition.ImageOnly;
        }

        label = EditorGUI.BeginProperty(position, label, property);
        position = EditorGUI.PrefixLabel(position, label);

        EditorGUI.BeginChangeCheck();

        // Get properties
        SerializedProperty valueProp = property.FindPropertyRelative("Value");
        SerializedProperty indexProp = property.FindPropertyRelative("InspectorIndex");

        // Calculate rect for configuration button
        Rect buttonRect = new Rect(position);
        buttonRect.yMin += popupStyle.margin.top;
        buttonRect.width = popupStyle.fixedWidth + popupStyle.margin.right;
        position.xMin = buttonRect.xMax;

        // Store old indent level and set it to 0, the PrefixLabel takes care of it
        int indent = EditorGUI.indentLevel;
        EditorGUI.indentLevel = 0;

        if (sorted == false)
        {
            System.Array.Sort(_choices);
            sorted = true;
        }
        _index = EditorGUI.Popup(buttonRect, indexProp.intValue, _choices, popupStyle);

        EditorGUI.PropertyField(position, valueProp);

        if (EditorGUI.EndChangeCheck())
        {
            indexProp.intValue = _index;
            valueProp.stringValue = _choices[indexProp.intValue];
            property.serializedObject.ApplyModifiedProperties();
        }
        EditorGUI.indentLevel = indent;
        EditorGUI.EndProperty();
    }

    private static bool sorted = false;
    private static string[] _choices = new string[] {
        "Alpha0",
        "Joystick4Button4",
        "Joystick4Button3",
        "Joystick4Button2",
        "Joystick4Button1",
        "Joystick4Button0",
        "Joystick3Button19",
        "Joystick3Button18",
        "Joystick3Button17",
        "Joystick4Button6",
        "Joystick3Button16",
        "Joystick3Button14",
        "Joystick3Button13",
        "Joystick3Button12",
        "Joystick3Button11",
        "Joystick3Button10",
        "Joystick3Button9",
        "Joystick3Button8",
        "Joystick3Button7",
        "Joystick3Button15",
        "Joystick4Button7",
        "Joystick4Button8",
        "Joystick4Button9",
        "Joy Axis 5-",
        "Joy Axis 4+",
        "Joy Axis 4-",
        "Joy Axis 3+",
        "Joy Axis 3-",
        "Joy Axis 2+",
        "Joy Axis 2-",
        "Joy Axis 1+",
        "Joy Axis 1-",
        "Joystick4Button19",
        "Joystick4Button18",
        "Joystick4Button17",
        "Joystick4Button16",
        "Joystick4Button15",
        "Joystick4Button14",
        "Joystick4Button13",
        "Joystick4Button12",
        "Joystick4Button11",
        "Joystick4Button10",
        "Joystick3Button6",
        "Joy Axis 5+",
        "Joystick3Button5",
        "Joystick3Button3",
        "Joystick1Button19",
        "Joystick1Button18",
        "Joystick1Button17",
        "Joystick1Button16",
        "Joystick1Button15",
        "Joystick1Button14",
        "Joystick1Button13",
        "Joystick1Button12",
        "Joystick2Button0",
        "Joystick1Button11",
        "Joystick1Button9",
        "Joystick1Button8",
        "Joystick1Button7",
        "Joystick1Button6",
        "Joystick1Button5",
        "Joystick1Button4",
        "Joystick1Button3",
        "Joystick1Button2",
        "Joystick1Button10",
        "Joystick2Button1",
        "Joystick2Button2",
        "Joystick2Button3",
        "Joystick3Button2",
        "Joystick3Button1",
        "Joystick3Button0",
        "Joystick2Button19",
        "Joystick2Button18",
        "Joystick2Button17",
        "Joystick2Button16",
        "Joystick2Button15",
        "Joystick2Button14",
        "Joystick2Button13",
        "Joystick2Button12",
        "Joystick2Button11",
        "Joystick2Button10",
        "Joystick2Button9",
        "Joystick2Button8",
        "Joystick2Button7",
        "Joystick2Button6",
        "Joystick2Button5",
        "Joystick2Button4",
        "Joystick3Button4",
        "Joy Axis 6-",
        "Joy Axis 6+",
        "Joy Axis 7-",
        "Joy3 Axis 9-",
        "Joy3 Axis 8+",
        "Joy3 Axis 8-",
        "Joy3 Axis 7+",
        "Joy3 Axis 7-",
        "Joy3 Axis 6+",
        "Joy3 Axis 6-",
        "Joy3 Axis 5+",
        "Joy3 Axis 9+",
        "Joy3 Axis 5-",
        "Joy3 Axis 4-",
        "Joy3 Axis 3+",
        "Joy3 Axis 3-",
        "Joy3 Axis 2+",
        "Joy3 Axis 2-",
        "Joy3 Axis 1+",
        "Joy3 Axis 1-",
        "Joy2 Axis 10+",
        "Joy3 Axis 4+",
        "Joy3 Axis 10-",
        "Joy3 Axis 10+",
        "Joy4 Axis 1-",
        "Joy4 Axis 10+",
        "Joy4 Axis 10-",
        "Joy4 Axis 9+",
        "Joy4 Axis 9-",
        "Joy4 Axis 8+",
        "Joy4 Axis 8-",
        "Joy4 Axis 7+",
        "Joy4 Axis 7-",
        "Joy4 Axis 6+",
        "Joy4 Axis 6-",
        "Joy4 Axis 5+",
        "Joy4 Axis 5-",
        "Joy4 Axis 4+",
        "Joy4 Axis 4-",
        "Joy4 Axis 3+",
        "Joy4 Axis 3-",
        "Joy4 Axis 2+",
        "Joy4 Axis 2-",
        "Joy4 Axis 1+",
        "Joy2 Axis 10-",
        "Joy2 Axis 9+",
        "Joy2 Axis 9-",
        "Joy2 Axis 8+",
        "Joy1 Axis 6+",
        "Joy1 Axis 6-",
        "Joy1 Axis 5+",
        "Joy1 Axis 5-",
        "Joy1 Axis 4+",
        "Joy1 Axis 4-",
        "Joy1 Axis 3+",
        "Joy1 Axis 3-",
        "Joy1 Axis 2+",
        "Joy1 Axis 2-",
        "Joy1 Axis 1+",
        "Joy1 Axis 1-",
        "Joy Axis 10+",
        "Joy Axis 10-",
        "Joy Axis 9+",
        "Joy Axis 9-",
        "Joy Axis 8+",
        "Joy Axis 8-",
        "Joy Axis 7+",
        "Joy1 Axis 7-",
        "Joystick1Button1",
        "Joy1 Axis 7+",
        "Joy1 Axis 8+",
        "Joy2 Axis 8-",
        "Joy2 Axis 7+",
        "Joy2 Axis 7-",
        "Joy2 Axis 6+",
        "Joy2 Axis 6-",
        "Joy2 Axis 5+",
        "Joy2 Axis 5-",
        "Joy2 Axis 4+",
        "Joy2 Axis 4-",
        "Joy2 Axis 3+",
        "Joy2 Axis 3-",
        "Joy2 Axis 2+",
        "Joy2 Axis 2-",
        "Joy2 Axis 1+",
        "Joy2 Axis 1-",
        "Joy1 Axis 10+",
        "Joy1 Axis 10-",
        "Joy1 Axis 9+",
        "Joy1 Axis 9-",
        "Joy1 Axis 8-",
        "Joystick1Button0",
        "Joystick4Button5",
        "JoystickButton18",
        "KeypadEquals",
        "KeypadEnter",
        "KeypadDivide",
        "KeypadMultiply",
        "Keypad9",
        "Keypad8",
        "Keypad7",
        "Keypad6",
        "KeypadMinus",
        "Keypad5",
        "Keypad3",
        "Keypad2",
        "Keypad1",
        "Keypad0",
        "F15",
        "F14",
        "F13",
        "F12",
        "Keypad4",
        "KeypadMultiply",
        "KeypadPeriod",
        "KeypadPlus",
        "Colon",
        "Clear",
        "Caret",
        "CapsLock",
        "Break",
        "Backspace",
        "Backslash",
        "BackQuote",
        "At",
        "Asterisk",
        "UpArrow",
        "RightArrow",
        "LeftArrow",
        "DownArrow",
        "Quote",
        "Ampersand",
        "AltGr",
        "None",
        "KeypadDivide",
        "F11",
        "F10",
        "F9",
        "F8",
        "J",
        "I",
        "H",
        "G",
        "F",
        "E",
        "D",
        "C",
        "B",
        "A",
        "Alpha9",
        "Alpha8",
        "Alpha7",
        "Alpha6",
        "Alpha5",
        "Alpha4",
        "Alpha3",
        "Alpha2",
        "Alpha1",
        "K",
        "Comma",
        "L",
        "N",
        "F7",
        "F6",
        "F5",
        "F4",
        "F3",
        "F2",
        "F1",
        "Z",
        "Y",
        "X",
        "W",
        "V",
        "U",
        "T",
        "S",
        "R",
        "Q",
        "JoystickButton19",
        "O",
        "M",
        "Delete",
        "P",
        "DoubleQuote",
        "Mouse Up",
        "Mouse6",
        "Mouse5",
        "Mouse4",
        "Mouse3",
        "Mouse2",
        "Mouse1",
        "Mouse0",
        "UpArrow",
        "Underscore",
        "Tab",
        "SysReq",
        "Space",
        "Slash",
        "Semicolon",
        "ScrollLock",
        "RightWindows",
        "RightShift",
        "RightParen",
        "Mouse Down",
        "RightControl",
        "Mouse Left",
        "Mouse Wheel Up",
        "Dollar",
        "JoystickButton17",
        "JoystickButton16",
        "JoystickButton15",
        "JoystickButton14",
        "JoystickButton13",
        "JoystickButton12",
        "JoystickButton11",
        "JoystickButton10",
        "JoystickButton9",
        "JoystickButton8",
        "JoystickButton7",
        "JoystickButton6",
        "JoystickButton4",
        "JoystickButton3",
        "JoystickButton2",
        "JoystickButton1",
        "JoystickButton0",
        "Mouse Wheel Down",
        "Mouse Right",
        "RightBracket",
        "JoystickButton5",
        "RightApple",
        "LeftControl",
        "LeftBracket",
        "LeftArrow",
        "LeftApple",
        "LeftAlt",
        "Insert",
        "Home",
        "Help",
        "Hash",
        "Greater",
        "Greater",
        "Slash",
        "Exclaim",
        "Escape",
        "Equals",
        "Return",
        "End",
        "RightArrow",
        "DownArrow",
        "LeftParen",
        "LeftShift",
        "Exclaim",
        "Less",
        "Return",
        "RightAlt",
        "LeftWindows",
        "Quote",
        "Question",
        "Print",
        "Hash",
        "Plus",
        "Period",
        "Pause",
        "Question",
        "PageDown",
        "Numlock",
        "Hash",
        "Greater",
        "Minus",
        "PageUp",
        "Less",
        "Menu"
    };
}
